// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tx.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tx struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parents              [][]byte `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"`
	Children             [][]byte `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	From                 []byte   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Sig                  []byte   `protobuf:"bytes,5,opt,name=sig,proto3" json:"sig,omitempty"`
	StateURI             string   `protobuf:"bytes,6,opt,name=stateURI,proto3" json:"stateURI,omitempty"`
	Patches              []*Patch `protobuf:"bytes,7,rep,name=patches,proto3" json:"patches,omitempty"`
	Recipients           [][]byte `protobuf:"bytes,8,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Checkpoint           bool     `protobuf:"varint,9,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Attachment           []byte   `protobuf:"bytes,10,opt,name=attachment,proto3" json:"attachment,omitempty"`
	Status               string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{0}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Tx) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Tx) GetChildren() [][]byte {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Tx) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Tx) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *Tx) GetStateURI() string {
	if m != nil {
		return m.StateURI
	}
	return ""
}

func (m *Tx) GetPatches() []*Patch {
	if m != nil {
		return m.Patches
	}
	return nil
}

func (m *Tx) GetRecipients() [][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *Tx) GetCheckpoint() bool {
	if m != nil {
		return m.Checkpoint
	}
	return false
}

func (m *Tx) GetAttachment() []byte {
	if m != nil {
		return m.Attachment
	}
	return nil
}

func (m *Tx) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Patch struct {
	Keypath              []byte   `protobuf:"bytes,1,opt,name=keypath,proto3" json:"keypath,omitempty"`
	Range                *Range   `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	Value                *any.Any `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patch) Reset()         { *m = Patch{} }
func (m *Patch) String() string { return proto.CompactTextString(m) }
func (*Patch) ProtoMessage()    {}
func (*Patch) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{1}
}

func (m *Patch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch.Unmarshal(m, b)
}
func (m *Patch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch.Marshal(b, m, deterministic)
}
func (m *Patch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch.Merge(m, src)
}
func (m *Patch) XXX_Size() int {
	return xxx_messageInfo_Patch.Size(m)
}
func (m *Patch) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch.DiscardUnknown(m)
}

var xxx_messageInfo_Patch proto.InternalMessageInfo

func (m *Patch) GetKeypath() []byte {
	if m != nil {
		return m.Keypath
	}
	return nil
}

func (m *Patch) GetRange() *Range {
	if m != nil {
		return m.Range
	}
	return nil
}

func (m *Patch) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Range struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fd2153dc07d3b5c, []int{2}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Range) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*Tx)(nil), "redwood.Tx")
	proto.RegisterType((*Patch)(nil), "redwood.Patch")
	proto.RegisterType((*Range)(nil), "redwood.Range")
}

func init() { proto.RegisterFile("tx.proto", fileDescriptor_0fd2153dc07d3b5c) }

var fileDescriptor_0fd2153dc07d3b5c = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x51, 0xb1, 0x6e, 0xc2, 0x30,
	0x10, 0x55, 0x62, 0x02, 0xe1, 0x40, 0xa8, 0xb2, 0x50, 0xe5, 0x32, 0x54, 0x11, 0xea, 0x10, 0x75,
	0x08, 0x52, 0xfb, 0x05, 0xed, 0xd6, 0xad, 0xb2, 0xda, 0xa5, 0x9b, 0x49, 0x4c, 0x62, 0x01, 0x76,
	0x64, 0x9b, 0x16, 0x7e, 0xaa, 0xdf, 0x58, 0xf9, 0x42, 0x10, 0xdd, 0xee, 0xbd, 0x77, 0xbe, 0x7b,
	0x7e, 0x07, 0xa9, 0x3f, 0x16, 0xad, 0x35, 0xde, 0xd0, 0x91, 0x95, 0xd5, 0x8f, 0x31, 0xd5, 0xe2,
	0xae, 0x36, 0xa6, 0xde, 0xc9, 0x15, 0xd2, 0xeb, 0xc3, 0x66, 0x25, 0xf4, 0xa9, 0xeb, 0x59, 0xfe,
	0xc6, 0x10, 0x7f, 0x1c, 0xe9, 0x0c, 0x62, 0x55, 0xb1, 0x28, 0x8b, 0xf2, 0x29, 0x8f, 0x55, 0x45,
	0x19, 0x8c, 0x5a, 0x61, 0xa5, 0xf6, 0x8e, 0xc5, 0x19, 0xc9, 0xa7, 0xbc, 0x87, 0x74, 0x01, 0x69,
	0xd9, 0xa8, 0x5d, 0x65, 0xa5, 0x66, 0x04, 0xa5, 0x0b, 0xa6, 0x14, 0x06, 0x1b, 0x6b, 0xf6, 0x6c,
	0x80, 0x73, 0xb0, 0xa6, 0x37, 0x40, 0x9c, 0xaa, 0x59, 0x82, 0x54, 0x28, 0xc3, 0x04, 0xe7, 0x85,
	0x97, 0x9f, 0xfc, 0x8d, 0x0d, 0xb3, 0x28, 0x1f, 0xf3, 0x0b, 0xa6, 0x79, 0xd8, 0xeb, 0xcb, 0x46,
	0x3a, 0x36, 0xca, 0x48, 0x3e, 0x79, 0x9a, 0x15, 0xe7, 0x4f, 0x14, 0xef, 0x81, 0xe7, 0xbd, 0x4c,
	0xef, 0x01, 0xac, 0x2c, 0x55, 0xab, 0xd0, 0x64, 0x8a, 0x4e, 0xae, 0x98, 0xa0, 0x97, 0x8d, 0x2c,
	0xb7, 0xad, 0x51, 0xda, 0xb3, 0x71, 0x16, 0xe5, 0x29, 0xbf, 0x62, 0x82, 0x2e, 0xbc, 0x17, 0x65,
	0xb3, 0x97, 0xda, 0x33, 0x40, 0x7b, 0x57, 0x0c, 0xbd, 0x85, 0x61, 0x70, 0x75, 0x70, 0x6c, 0x82,
	0x1e, 0xcf, 0x68, 0xe9, 0x20, 0x41, 0x27, 0x21, 0xa2, 0xad, 0x3c, 0xb5, 0xc2, 0x37, 0xe7, 0xdc,
	0x7a, 0x48, 0x1f, 0x20, 0xb1, 0x42, 0xd7, 0x92, 0xc5, 0x59, 0xf4, 0xef, 0x0b, 0x3c, 0xb0, 0xbc,
	0x13, 0xe9, 0x23, 0x24, 0xdf, 0x62, 0x77, 0x90, 0x8c, 0x60, 0xd7, 0xbc, 0xe8, 0x8e, 0x54, 0xf4,
	0x47, 0x2a, 0x5e, 0xf4, 0x89, 0x77, 0x2d, 0xcb, 0x15, 0x24, 0xf8, 0x96, 0xce, 0x21, 0x71, 0x5e,
	0x58, 0x8f, 0x2b, 0x09, 0xef, 0x40, 0xc8, 0x58, 0xea, 0x0a, 0xd7, 0x11, 0x1e, 0xca, 0xd7, 0xc1,
	0x57, 0xdc, 0xae, 0xd7, 0x43, 0x9c, 0xf5, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x52, 0x2b, 0x73,
	0x7b, 0x13, 0x02, 0x00, 0x00,
}
