// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	prototree "redwood.dev/swarm/prototree"

	swarm "redwood.dev/swarm"
)

// TreeTransport is an autogenerated mock type for the TreeTransport type
type TreeTransport struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *TreeTransport) Close() {
	_m.Called()
}

// Name provides a mock function with given fields:
func (_m *TreeTransport) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewPeerConn provides a mock function with given fields: ctx, dialAddr
func (_m *TreeTransport) NewPeerConn(ctx context.Context, dialAddr string) (swarm.PeerConn, error) {
	ret := _m.Called(ctx, dialAddr)

	var r0 swarm.PeerConn
	if rf, ok := ret.Get(0).(func(context.Context, string) swarm.PeerConn); ok {
		r0 = rf(ctx, dialAddr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(swarm.PeerConn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, dialAddr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OnAckReceived provides a mock function with given fields: handler
func (_m *TreeTransport) OnAckReceived(handler prototree.AckReceivedCallback) {
	_m.Called(handler)
}

// OnTxReceived provides a mock function with given fields: handler
func (_m *TreeTransport) OnTxReceived(handler prototree.TxReceivedCallback) {
	_m.Called(handler)
}

// OnWritableSubscriptionOpened provides a mock function with given fields: handler
func (_m *TreeTransport) OnWritableSubscriptionOpened(handler prototree.WritableSubscriptionOpenedCallback) {
	_m.Called(handler)
}

// ProvidersOfStateURI provides a mock function with given fields: ctx, stateURI
func (_m *TreeTransport) ProvidersOfStateURI(ctx context.Context, stateURI string) (<-chan prototree.TreePeerConn, error) {
	ret := _m.Called(ctx, stateURI)

	var r0 <-chan prototree.TreePeerConn
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan prototree.TreePeerConn); ok {
		r0 = rf(ctx, stateURI)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan prototree.TreePeerConn)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, stateURI)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields:
func (_m *TreeTransport) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
